fixes #51 - move dotenv
CenterForDigitalHumanities/TinyNode pull request #81
Opened 2024-05-14 17:31 UTC by cubap

2024-05-14 19:01 UTC, cubap commented
hmm. @thehabes This runs locally fine, but also seems to be not finding the .env file. I moved where it is called for, of course, so is there perhaps a setting in the runner that needs to be adjusted?

2024-05-15 18:36 UTC, thehabes requested changes
Unfortunately it does not work locally either.
![image](https://github.com/CenterForDigitalHumanities/TinyNode/assets/3287006/a9f36fba-55b0-4d09-9213-e8418afa9287)

I believe you have moved dotenv in such a way that the test files (or other files) that process `.env` variables no longer have that import.  For tests that need them, they need to `import dotenv` directly or via another imported module that happened to import it.

2024-05-15 20:31 UTC, cubap commented
yeah, I'll wait and see how it turns out when the precursors are merged.

2024-05-20 19:15 UTC, thehabes approved these changes

2024-05-20 19:17 UTC, merged